# Generated by Django 5.2.6 on 2025-10-08 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=256, unique=True),
        ),
    ]
